### ISSUE TITLE
PHP Warning: Cannot modify header information - headers already sent by (output started at /var/www/w/maintenance/includes/Maintenance.php:450) in /var/www/w/extensions/ExternalRedirect/ExternalRedirect.php on line 65

### ISSUE THREAD

**Issue by adrelanos** [DavisNT/ExternalRedirect#3]
Getting this when running some maintenance scripts.

    sudo -u www-data php /var/www/w/maintenance/refreshLinks.php

> PHP Warning:  Cannot modify header information - headers already sent by (output started at /var/www/w/maintenance/includes/Maintenance.php:450) in /var/www/w/extensions/ExternalRedirect/ExternalRedirect.php on line 65

**Comment by DavisNT** [comment]
@adrelanos Thank you for reporting this issue!
It should be fixed in [v1.2.1](https://github.com/DavisNT/ExternalRedirect/releases/tag/v1.2.1).

**Comment by adrelanos** [comment]
Yes, it's fixed.
Thank you so much!
